apiVersion: v1
kind: Secret
metadata:
  name: quickstart-config
stringData:
  logstash.yml: |-
    pipeline.workers: 4
    log.level: debug
    api.http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
