apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: np
  name: np
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: np
  type: NodePort
status:
  loadBalancer: {}
